openapi: 3.0.3
info:
  title: Industrial API
  description: Active assets specifications
  version: 1.0.1
paths:
  /variables:
    get:
      summary: Get the variables of the asset
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Variable'
  /state:
    get:
      summary: Get current state of the asset
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
  /operations:
    get:
      summary: Get executable operations of the asset
      responses:
        '200':
          description: List of executable operations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operation'
  /operation/{operationId}:
    post:
      summary: Execute an operation of the asset
      parameters:
        - in: path
          name: operationId
          schema:
            $ref: '#/components/schemas/Operation/properties/operationID'
          required: true
          description: Operation id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operation/properties/parameters'
        required: false
        description: Parameters of the operation
      responses:
        '200':
          description: Operation executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'

components:
  schemas:
    Variable:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        unitMeasure:
          type: string
    AssVariable:
      type: object
      properties:
        variable:
          $ref: '#/components/schemas/Variable'
        value:
          type: string
          description: Variable value
    State:
      type: array
      items:
        $ref: '#/components/schemas/AssVariable'
      description: State of the asset
    Operation:
      type: object
      properties:
        operationID:
          type: string
          description: Operation ID
        preconditions:
          type: string
        effects:
          type: array
          items:
            $ref: '#/components/schemas/Effect'
          description: Effects of the operation
        parameters:
          type: object
          additionalProperties:
            type: string
          description: Parameters of the operation
    Effect:
      type: object
      properties:
        nextState:
          $ref: '#/components/schemas/State'
        reward:
          type: number
          format: double
        probability:
          type: number
          format: double
      description: Next state, probability and reward